import { HALLOWEEN, VALENTINE, CHRISTMAS } from "./constants";

export const breeds = [
  {
    name: "Aegis (Enraged)",
    male: true,
    female: false,
    holiday: CHRISTMAS,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Aegis"],
  },
  {
    name: "Aegis (Pacified)",
    male: true,
    female: false,
    holiday: CHRISTMAS,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Aegis"],
  },
  {
    name: "Aeon Wyvern",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Aeria Gloris",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Aether Wyvern",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Albino",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Alcedine Wyvern (Blue)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Alcedine Wyvern"],
  },
  {
    name: "Alcedine Wyvern (Brown)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Alcedine Wyvern"],
  },
  {
    name: "Almerald",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Amalthean",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Anagallis",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Antarean",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Aqualis",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Aranoas",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Arcana",
    male: true,
    female: true,
    shiny: false,
    holiday: HALLOWEEN,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Aria",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Arsani",
    male: false,
    female: true,
    holiday: VALENTINE,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Ash",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Avatar of Change",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Avatar of Creation",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Avatar of Destruction",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Avea Pygmy",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: true,
    offspringTypes: [],
  },
  {
    name: "Azure Glacewing",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Baikala (Blue)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: true,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Baikala (Green)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: true,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Balloon",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Bauta",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: true,
    pygmy: false,
    offspringTypes: ["Bauta", "Jester"],
  },
  {
    name: "Black",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Black Alt.",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Black Capped Teimarr",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Black Marrow",
    male: true,
    female: true,
    shiny: false,
    holiday: HALLOWEEN,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Black Tea",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Black Truffle",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Blacktip",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Blancblack",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: true,
    pygmy: false,
    offspringTypes: ["Blancblack", "Jester"],
  },
  {
    name: "Bleeding Moon",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Blue-Banded",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Blusang Lindwurm",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Bolt",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Boreal",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Bright-Breasted Wyvern",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Brimstone",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Brute",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Caligene",
    male: true,
    female: true,
    shiny: false,
    holiday: HALLOWEEN,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Candelabra",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Canopy",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Carina",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Carmine Wyvern",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Cassare",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Cavern Lurker",
    male: true,
    female: true,
    shiny: false,
    holiday: HALLOWEEN,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Celestial",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Cloudplume",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Coastal Waverunner",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Coastal Waverunner", "Storm-Rider"],
  },
  {
    name: "Common Pygmy",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: true,
    offspringTypes: [],
  },
  {
    name: "Copper (Liver of Sulfur)",
    male: true,
    female: true,
    shiny: true,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [
      "Copper (Liver of Sulfur)",
      "Copper (Rainbow)",
      "Copper (Verdigris)",
    ],
  },
  {
    name: "Copper (Rainbow)",
    male: true,
    female: true,
    shiny: true,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [
      "Copper (Liver of Sulfur)",
      "Copper (Rainbow)",
      "Copper (Verdigris)",
    ],
  },
  {
    name: "Copper (Verdigris)",
    male: true,
    female: true,
    shiny: true,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [
      "Copper (Liver of Sulfur)",
      "Copper (Rainbow)",
      "Copper (Verdigris)",
    ],
  },
  {
    name: "Coral Pygmy Wyvern",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: true,
    offspringTypes: [],
  },
  {
    name: "Crimson Flare Pygmy",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: true,
    offspringTypes: ["Crimson Flare Pygmy, Dusk Pygmy"],
  },
  {
    name: "Crystalline",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Dark Green",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Dark Green Alt.",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Lumina (Dark)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Lumina (Dark)", "Lumina (Light)"],
  },
  {
    name: "Dark Myst Pygmy",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: true,
    offspringTypes: [],
  },
  {
    name: "Glory Drake (Day)",
    male: true,
    female: true,
    shiny: false,
    drake: true,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Daydream",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Daydream", "Soulpeace"],
  },
  {
    name: "Deep Sea",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Deep Sea", "Two-Finned Bluna"],
  },
  {
    name: "Desipis",
    male: true,
    female: true,
    shiny: false,
    holiday: HALLOWEEN,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Diamondwing",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Dorsal (Purple)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Dorsal (Red)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Duotone",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: true,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Dusk Pygmy",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: true,
    offspringTypes: [],
  },
  {
    name: "Electric",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Electric", "Storm-Rider"],
  },
  {
    name: "Ember",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Erador Lindwyrm",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Falconiform Wyvern",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Fell",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Fever Wyvern",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Fire Gem (Blue)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Fire Gem (Green)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Fire Gem (Red)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Flamingo Wyvern",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Floral-Crowned",
    male: true,
    female: false,
    holiday: VALENTINE,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Floret Wyvern (Gold)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Floret Wyvern (Purple)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Freckled",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Frilled",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Frostbite",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Galvanic Wyvern",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Garland",
    male: false,
    female: true,
    shiny: false,
    holiday: CHRISTMAS,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Geminae",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Gemshard (Blue)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Gemshard (Green)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Gemshard (Red)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Geode",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Gilded Bloodscale",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Glaucus Drake",
    male: true,
    female: true,
    shiny: false,
    drake: true,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Glowback Pygmy",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: true,
    offspringTypes: [],
  },
  {
    name: "Gold",
    male: true,
    female: true,
    shiny: true,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Gold-Horned Tangar",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Golden Wyvern",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Grave",
    male: true,
    female: true,
    shiny: false,
    holiday: HALLOWEEN,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Greater Spotted Drake",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Green",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Green", "Geode"],
  },
  {
    name: "Guardian",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Guardian of Nature",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [
      "Avatar of Change",
      "Avatar of Creation",
      "Avatar of Destruction",
    ],
  },
  {
    name: "Harvest",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Heartseeker",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Heartstealing",
    male: false,
    female: true,
    shiny: false,
    holiday: VALENTINE,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Hellfire Wyvern",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Hellfire Wyvern", "Hellhorse"],
  },
  {
    name: "Hellhorse",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Holly",
    male: true,
    female: true,
    shiny: false,
    holiday: CHRISTMAS,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Honey Drake",
    male: true,
    female: true,
    shiny: false,
    drake: true,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Hooktalon",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: true,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Horse",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Horse", "Hellhorse"],
  },
  {
    name: "Howler Drake",
    male: true,
    female: true,
    shiny: false,
    drake: true,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Ice",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Imperial Fleshcrowne",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Jester",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: true,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Khusa",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Kingcrowne",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Kohraki",
    male: true,
    female: true,
    shiny: false,
    holiday: HALLOWEEN,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Kovos Pygmy",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: true,
    offspringTypes: [],
  },
  {
    name: "Kyanite Pygmy",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: true,
    offspringTypes: [],
  },
  {
    name: "Labradorite",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Lacula",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Leodon",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Lihnseyre",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Lumina (Light)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Lumina (Light)", "Lumina (Dark)"],
  },
  {
    name: "Luminox Wyvern",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Lunar Herald (Bronze)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Lunar Herald (Gold)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Lunar Herald (Indigo)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Lunar Herald (Silver)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Magelight Pygmy Wyvern",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: true,
    offspringTypes: [],
  },
  {
    name: "Magi",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Magi", "Shallow Water"],
  },
  {
    name: "Magma",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Mariner Pygmy",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Melismor",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Mimic Pygmy",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: true,
    offspringTypes: [],
  },
  {
    name: "Mint",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Misfit Pygmy",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: true,
    offspringTypes: [],
  },
  {
    name: "Mistletoe",
    male: true,
    female: true,
    shiny: false,
    holiday: CHRISTMAS,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Monarch",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Moonstone",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Morphodrake",
    male: true,
    female: true,
    shiny: false,
    drake: true,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Mutamore",
    male: true,
    female: false,
    shiny: false,
    holiday: VALENTINE,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Nebula (Blue)",
    male: false,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Nebula", "Carina"],
  },
  {
    name: "Nebula (Green)",
    male: true,
    female: false,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Nebula", "Carina"],
  },
  {
    name: "Nebula (Purple)",
    male: true,
    female: false,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Nebula", "Carina"],
  },
  {
    name: "Nebula (Red)",
    male: false,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Nebula", "Carina"],
  },
  {
    name: "Neotropical",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Nexus",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: true,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Nhiostrife Wyvern",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Glory Drake (Night)",
    male: true,
    female: true,
    shiny: false,
    drake: true,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Nilia Pygmy",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: true,
    offspringTypes: ["Nilia Pygmy", "Dusk Pygmy"],
  },
  {
    name: "Nocturne",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Ochredrake",
    male: true,
    female: true,
    shiny: false,
    drake: true,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Olive",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Omen Wyrm",
    male: true,
    female: true,
    shiny: false,
    holiday: HALLOWEEN,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Pargulus Pygmy (Blue)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: true,
    offspringTypes: [],
  },
  {
    name: "Pargulus Pygmy (Green)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: true,
    offspringTypes: [],
  },
  {
    name: "Pargulus Pygmy (Red)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: true,
    offspringTypes: [],
  },
  {
    name: "Pillow",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Pink",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Pipio Pygmy",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: true,
    offspringTypes: [],
  },
  {
    name: "Plated Colossus",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Pumpkin",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: true,
    offspringTypes: [],
  },
  {
    name: "Purple",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Purple", "Ultraviolet"],
  },
  {
    name: "Pyralspite (Almadine)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Pyralspite (Pyrope)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Pyralspite (Spessartine)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Pyrovar",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Radiant Angel",
    male: true,
    female: false,
    shiny: false,
    holiday: VALENTINE,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Razorcrest Wyvern",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Red",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Red-Finned Tidal",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Red-Tailed Pygmy Wyrm",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: true,
    offspringTypes: [],
  },
  {
    name: "Ribbon Dancer",
    male: false,
    female: true,
    shiny: false,
    holiday: CHRISTMAS,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Ridgewing (Purple)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Ridgewing (Purple)", "Ridgewing (Tan)", "Carina"],
  },
  {
    name: "Ridgewing (Tan)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Ridgewing (Purple)", "Ridgewing (Tan)", "Carina"],
  },
  {
    name: "Rift Wyrm",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Risensong",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Risensong", "Setsong"],
  },
  {
    name: "Rosebud",
    male: false,
    female: true,
    shiny: false,
    holiday: VALENTINE,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Royal Blue",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Royal Crimson",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Sakuhana Wyvern",
    male: false,
    female: true,
    shiny: false,
    holiday: VALENTINE,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Sandwaste",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Sapo",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Sapphire",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Scimitar-Wing Wyvern",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Script",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Seasonal (Autumn)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [
      "Seasonal (Summer)",
      "Seasonal (Spring)",
      "Seasonal (Winter)",
    ],
  },
  {
    name: "Seasonal (Spring)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [
      "Seasonal (Summer)",
      "Seasonal (Autumn)",
      "Seasonal (Winter)",
    ],
  },
  {
    name: "Seasonal (Summer)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [
      "Seasonal (Winter)",
      "Seasonal (Spring)",
      "Seasonal (Winter)",
    ],
  },
  {
    name: "Seasonal (winter)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [
      "Seasonal (Summer)",
      "Seasonal (Spring)",
      "Seasonal (Autumn)",
    ],
  },
  {
    name: "Seawyrm Pygmy",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: true,
    offspringTypes: [],
  },
  {
    name: "Seragamma Wyvern",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Setsong",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Risensong", "Setsong"],
  },
  {
    name: "Shadow Walker",
    male: true,
    female: true,
    shiny: false,
    holiday: HALLOWEEN,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Shallow Water",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Shimmer-scale (Bronze)",
    male: true,
    female: true,
    shiny: true,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Shimmer-scale (Gold)",
    male: true,
    female: true,
    shiny: true,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Shimmer-scale (Silver)",
    male: true,
    female: true,
    shiny: true,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Silver",
    male: true,
    female: true,
    shiny: true,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Sinii Krai",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Siyat (Blue)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Siyat (Green)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Siyat (Purple)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Sinomorph",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [
      "Zyuumorph (Black)",
      "Zyuumorph (Pink)",
      "Zyuumorph (Blue)",
      "Zyuumorph (White)",
      "Zyuumorph (Yellow)",
      "Zyuumorph (Red)",
    ],
  },
  {
    name: "Skysilk",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Skywing",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Two-Finned Bluna", "Skywing"],
  },
  {
    name: "Snow",
    male: true,
    female: false,
    holiday: CHRISTMAS,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Snow Angel (Full Gold)",
    male: false,
    female: true,
    holiday: CHRISTMAS,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Snow Angel (Tri-Colored)",
    male: false,
    female: true,
    shiny: false,
    holiday: CHRISTMAS,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Snow Angel (White-Tipped)",
    male: false,
    female: true,
    shiny: false,
    holiday: CHRISTMAS,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Solstice (Blue)",
    male: true,
    female: true,
    shiny: false,
    holiday: CHRISTMAS,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Solstice (Rosy)",
    male: true,
    female: true,
    shiny: false,
    holiday: CHRISTMAS,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Soulpeace",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Soulstone",
    male: false,
    female: true,
    holiday: VALENTINE,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Speckle-Throated",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Spinel (Red)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Spinel (Red)", "Spinel (Green)"],
  },
  {
    name: "Spinel (Green)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Spinel (Red)", "Spinel (Green)"],
  },
  {
    name: "Spirit Ward",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Spitfire",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Spitfire", "Ultraviolet"],
  },
  {
    name: "Split",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: true,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Spotted Greenwing",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Starsinger",
    male: false,
    female: true,
    shiny: false,
    holiday: CHRISTMAS,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Stone",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Stone", "Geode"],
  },
  {
    name: "Storm",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Storm-Rider",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Stratos",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Striped (Black)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [
      "Striped (White)",
      "Striped (Blue)",
      "Striped (Green)",
      "Striped (Red)",
    ],
  },
  {
    name: "Striped (Blue)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [
      "Striped (White)",
      "Striped (Black)",
      "Striped (Green)",
      "Striped (Red)",
    ],
  },
  {
    name: "Striped (Green)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [
      "Striped (White)",
      "Striped (Blue)",
      "Striped (Black)",
      "Striped (Red)",
    ],
  },
  {
    name: "Striped (Red)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [
      "Striped (White)",
      "Striped (Blue)",
      "Striped (Green)",
      "Striped (Black)",
    ],
  },
  {
    name: "Striped (White)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [
      "Striped (Black)",
      "Striped (Blue)",
      "Striped (Green)",
      "Striped (Red)",
    ],
  },
  {
    name: "Striped River",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Sunrise",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Sunrise", "Risensong"],
  },
  {
    name: "Sunset",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Sunset", "Setsong"],
  },
  {
    name: "Sunsong Amphiptere",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Sunsong Amphiptere", "Risensong", "Setsong"],
  },
  {
    name: "Sunstone",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Swallowtail",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Sweetling (Black)",
    male: true,
    female: false,
    shiny: false,
    holiday: VALENTINE,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Sweetling (Pink)",
    male: true,
    female: false,
    shiny: false,
    holiday: VALENTINE,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Tarantula Hawk Drake",
    male: true,
    female: true,
    shiny: false,
    drake: true,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Tatterdrake",
    male: true,
    female: true,
    shiny: false,
    drake: true,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Tercorn",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Terrae",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Tetra",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Thunder",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Tinsel (Bronze)",
    male: true,
    female: true,
    shiny: true,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Tinsel (Gold)",
    male: true,
    female: true,
    shiny: true,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Tinsel (Silver)",
    male: true,
    female: true,
    shiny: true,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Tri-Horn Wyvern",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Tsunami Wyvern",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Turpentine",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Two-Finned Bluna",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Two-Headed Lindwurm (Purple)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: true,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Two-Headed Lindwurm (Green)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: true,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Ultraviolet",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Ultraviolet", "Spitfire", "Purple"],
  },
  {
    name: "Undine (Green)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Amalthean", "Undine (Green)", "Undine (Yellow)"],
  },
  {
    name: "Undine (Yellow)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Amalthean", "Undine (Green)", "Undine (Yellow)"],
  },
  {
    name: "Valentine",
    male: false,
    female: true,
    shiny: false,
    holiday: VALENTINE,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Venturis",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Vremya Drake",
    male: true,
    female: true,
    shiny: false,
    drake: true,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Water",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Water", "Two-Finned Bluna", "Shallow Water"],
  },
  {
    name: "Water Walker",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Waterhorse",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Whiptail",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "White",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Amalthean", "Soulpeace", "White"],
  },
  {
    name: "Winter Magi",
    male: true,
    female: false,
    shiny: false,
    holiday: CHRISTMAS,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Wintertide",
    male: true,
    female: false,
    shiny: false,
    holiday: CHRISTMAS,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Witchlight",
    male: true,
    female: true,
    shiny: false,
    holiday: HALLOWEEN,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Wrapping-Wing",
    male: true,
    female: false,
    shiny: false,
    holiday: CHRISTMAS,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Xenowyrm (Astrapi)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [
      "Xenowyrm (Chrono)",
      "Xenowyrm (Gaia)",
      "Xenowyrm (Mageia)",
      "Xenowyrm (Pyro),",
      "Xenowyrm (Thalassa)",
    ],
  },
  {
    name: "Xenowyrm (Chrono)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [
      "Xenowyrm (Astrapi)",
      "Xenowyrm (Gaia)",
      "Xenowyrm (Mageia)",
      "Xenowyrm (Pyro),",
      "Xenowyrm (Thalassa)",
    ],
  },
  {
    name: "Xenowyrm (Gaia)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [
      "Xenowyrm (Astrapi)",
      "Xenowyrm (Chrono)",
      "Xenowyrm (Mageia)",
      "Xenowyrm (Pyro),",
      "Xenowyrm (Thalassa)",
    ],
  },
  {
    name: "Xenowyrm (Mageia)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [
      "Xenowyrm (Astrapi)",
      "Xenowyrm (Gaia)",
      "Xenowyrm (Chrono)",
      "Xenowyrm (Pyro),",
      "Xenowyrm (Thalassa)",
    ],
  },
  {
    name: "Xenowyrm (Pyro)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [
      "Xenowyrm (Astrapi)",
      "Xenowyrm (Gaia)",
      "Xenowyrm (Mageia)",
      "Xenowyrm (Chrono),",
      "Xenowyrm (Thalassa)",
    ],
  },
  {
    name: "Xenowyrm (Thalassa)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [
      "Xenowyrm (Astrapi)",
      "Xenowyrm (Gaia)",
      "Xenowyrm (Mageia)",
      "Xenowyrm (Pyro),",
      "Xenowyrm (Chrono)",
    ],
  },
  {
    name: "Xol (Blue)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Xol"],
  },
  {
    name: "Xol (Red)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: ["Xol"],
  },
  {
    name: "Yellow-Crowned",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Yulebuck",
    male: true,
    female: false,
    shiny: false,
    holiday: CHRISTMAS,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Zyumorph (Black)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Zyumorph (Blue)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Zyumorph (Pink)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Zyumorph (Red)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Zyumorph (White)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
  {
    name: "Zyumorph (Yellow)",
    male: true,
    female: true,
    shiny: false,
    drake: false,
    twoHead: false,
    pygmy: false,
    offspringTypes: [],
  },
];

export const getMaleBreeds = () => {
  return breeds.filter((breed) => breed.male == true).sort(compareBreeds);
};

export const getFemaleBreeds = () => {
  return breeds.filter((breed) => breed.female == true).sort(compareBreeds);
};

export const getRegularBreeds = () => {
  return breeds
    .filter(
      (breed) =>
        breed.drake == false && breed.pygmy == false && breed.twoHead == false
    )
    .sort(compareBreeds);
};

export const getDrakeBreeds = () => {
  return breeds.filter((breed) => breed.drake == true).sort(compareBreeds);
};

export const getTwoHeadedBreeds = () => {
  return breeds.filter((breed) => breed.twoHead == true).sort(compareBreeds);
};

export const getPygmyBreeds = () => {
  return breeds.filter((breed) => breed.pygmy == true).sort(compareBreeds);
};

/**
 * Compares two breeds together and sorts them by name
 * @param a
 * @param b
 */
function compareBreeds(a, b) {
  var nameA = a.name.toUpperCase();
  var nameB = b.name.toUpperCase();
  if (nameA < nameB) {
    return -1;
  } else if (nameA > nameB) {
    return 1;
  } else {
    return 0;
  }
}
